### ISSUE TITLE
Cannot use modelDefault in v3.0.4

### ISSUE THREAD

**Issue by monfortm** [grapoza/vue-tree#277]
Hello @grapoza,

I am using `"@grapoza/vue-tree": "3.0.4"`, basing my understanding on the related [3.0.4 documentation](https://grapoza.github.io/vue-tree/3.0.4/)

**Describe the bug**
Cannot use `modelDefaults`. Package complains `id` and `label` are required when model default redefines what key should be used as `id` and `label` (see consol error in CodeSandbox)

**To Reproduce**
[Minimal example on CodeSanbox](https://codesandbox.io/s/funny-sid-ygn5pd)

**Expected behavior**
Expecting to be able to spawn a tree with non default data model, as described in [https://grapoza.github.io/vue-tree/3.0.4/demos.html#setting-defaults](https://grapoza.github.io/vue-tree/3.0.4/demos.html#setting-defaults)

 - Browser: Firefox@latest

**Additional context**
I understand this is an old version, but I was expecting it to work as is. The app I am working on has not yet been migrated such that I can;t use latest version of `vue-tree`

Thanks for the work tho, the lib looks nice.

**Comment by grapoza** [comment]
As if that wasn't bad enough on it's own, the demos page in the old documentation isn't even usable due to a bad unpkg reference for Vue itself:
`<script src="https://unpkg.com/vue/dist/vue.min.js"></script>` which should instead be `<script src=https://unpkg.com/vue@2.7.13/dist/vue.min.js"></script>`

I'll look into this and issue a 3.0.5 version. Thanks for finding this, and extra thanks for providing the reproduction. It makes my life so much easier.

**Comment by grapoza** [comment]
OK, I found the issue with the sandbox! It looks like there was a missing `s` on the attribute (so it was `:model-default=` instead of `:model-defaults=`. Once I fixed the attribute it rendered the tree as expected. Here's a [forked sandbox](https://codesandbox.io/s/hungry-water-iocd45) with the fix. Does this address the issue you were seeing, or was there anything else you saw (besides the documentation fix I noted, which I'm working on)?

**Comment by monfortm** [comment]
Thank you for the prompt answer and the fix. 
I feel stupid, years of programming and this stuff still happens to me. The missing `s` fixed it. I will be more careful in the future!

Nothing else spotted so far, I'm just starting with the lib. Wish I could use the latest version but very happy to see that older versions are still under your radar and that you kept the doc online. Neat.

> As if that wasn't bad enough on it's own, the demos page in the old documentation isn't even usable due to a bad unpkg reference for Vue itself

I did not even catch this, I thought the blank squares in the docs were just section separators ^^ 

Thank you!

**Comment by grapoza** [comment]
Hey, I got the demos in [the latest version of the 3.x docs](https://grapoza.github.io/vue-tree/3.0.5/demos.html) all fixed up. Hopefully this will be more helpful, sorry they were so broken without me noticing! I do need to update that "old version" notice in the new docs to point to 3.0.5 instead of 3.0.4 as well...

I'll close this issue out for now. Thanks for giving feedback on the tree, it's a lot more motivating than never hearing anything. :) Feel free to throw in enhancement requests as well if you hit anything you think is missing!
